"""create execution_runs table

Revision ID: 155d3c623c02
Revises: 647f42fe55ee
Create Date: 2026-03-21 00:46:02.192817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155d3c623c02'
down_revision: Union[str, Sequence[str], None] = '647f42fe55ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', sa.Text(), nullable=True),
    sa.Column('output_snapshot', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_runs_id'), 'execution_runs', ['id'], unique=False)
    op.create_index(op.f('ix_execution_runs_task_id'), 'execution_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_runs_task_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_id'), table_name='execution_runs')
    op.drop_table('execution_runs')
    # ### end Alembic commands ###
