"""new execution_run contract

Revision ID: 1f128b4c74cf
Revises: e6cbc04ce087
Create Date: 2026-04-02 22:48:22.625410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f128b4c74cf"
down_revision: Union[str, Sequence[str], None] = "e6cbc04ce087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("execution_runs", sa.Column("files_read", sa.Text(), nullable=True))
    op.add_column("execution_runs", sa.Column("change_dependencies", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("execution_runs", "change_dependencies")
    op.drop_column("execution_runs", "files_read")
    # ### end Alembic commands ###
