"""new execution_run contract v2

Revision ID: 4a8d17117be2
Revises: 1f128b4c74cf
Create Date: 2026-04-02 23:07:19.832103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a8d17117be2"
down_revision: Union[str, Sequence[str], None] = "1f128b4c74cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("execution_runs", sa.Column("changed_files", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("execution_runs", "changed_files")
    # ### end Alembic commands ###
