"""expand task details

Revision ID: 5bcd9435eed5
Revises: d35f0c697f44
Create Date: 2026-03-21 01:15:54.001910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcd9435eed5'
down_revision: Union[str, Sequence[str], None] = 'd35f0c697f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('tasks', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('implementation_notes', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('technical_constraints', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('out_of_scope', sa.Text(), nullable=True))

    op.add_column(
        'tasks',
        sa.Column('priority', sa.String(length=50), nullable=False, server_default='medium')
    )

    op.alter_column('tasks', 'priority', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'out_of_scope')
    op.drop_column('tasks', 'technical_constraints')
    op.drop_column('tasks', 'acceptance_criteria')
    op.drop_column('tasks', 'implementation_notes')
    op.drop_column('tasks', 'objective')
    op.drop_column('tasks', 'summary')
    # ### end Alembic commands ###
