"""new parameter in tasks

Revision ID: 644e34a21eef
Revises: 14b764188bf0
Create Date: 2026-03-25 22:09:56.842745

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "644e34a21eef"
down_revision: Union[str, Sequence[str], None] = "14b764188bf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
