"""add_requirements_draft_to_conversation

Revision ID: 667efb597d86
Revises: d558c9aaaf7a
Create Date: 2026-05-10 19:02:40.881209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667efb597d86'
down_revision: Union[str, Sequence[str], None] = 'd558c9aaaf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('requirements_draft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'requirements_draft')
    # ### end Alembic commands ###
