"""add_supervisor_reports_and_agent_evaluations

Revision ID: c489e0b5821d
Revises: a3b4c5d6e7f8
Create Date: 2026-05-29 20:20:19.361014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c489e0b5821d"
down_revision: Union[str, Sequence[str], None] = "a3b4c5d6e7f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supervisor_reports",
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("analyzed_run_ids", sa.JSON(), nullable=True),
        sa.Column("synthesis", sa.Text(), nullable=True),
        sa.Column("overall_verdict", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_index(
        op.f("ix_supervisor_reports_project_id"), "supervisor_reports", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_supervisor_reports_report_id"), "supervisor_reports", ["report_id"], unique=False
    )
    op.create_table(
        "agent_evaluations",
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("execution_run_ids_analyzed", sa.JSON(), nullable=True),
        sa.Column("system_versions_seen", sa.JSON(), nullable=True),
        sa.Column("verdict", sa.String(length=50), nullable=True),
        sa.Column("findings", sa.Text(), nullable=True),
        sa.Column("issues", sa.JSON(), nullable=True),
        sa.Column("suggestions", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["supervisor_reports.report_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("report_id", "agent_name"),
    )
    op.create_index(
        op.f("ix_agent_evaluations_project_id"), "agent_evaluations", ["project_id"], unique=False
    )
    op.drop_index(op.f("ix_conversation_messages_task_id"), table_name="conversation_messages")
    op.drop_constraint(
        op.f("conversation_messages_task_id_fkey"), "conversation_messages", type_="foreignkey"
    )
    op.drop_column("conversation_messages", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_messages",
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("conversation_messages_task_id_fkey"),
        "conversation_messages",
        "tasks",
        ["task_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_conversation_messages_task_id"), "conversation_messages", ["task_id"], unique=False
    )
    op.drop_index(op.f("ix_agent_evaluations_project_id"), table_name="agent_evaluations")
    op.drop_table("agent_evaluations")
    op.drop_index(op.f("ix_supervisor_reports_report_id"), table_name="supervisor_reports")
    op.drop_index(op.f("ix_supervisor_reports_project_id"), table_name="supervisor_reports")
    op.drop_table("supervisor_reports")
    # ### end Alembic commands ###
