"""new attribute in tasks for agents

Revision ID: dcc5be4a4ee5
Revises: 644e34a21eef
Create Date: 2026-03-25 23:18:14.170955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcc5be4a4ee5"
down_revision: Union[str, Sequence[str], None] = "644e34a21eef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "execution_runs",
        sa.Column("execution_agent_sequence", sa.Text(), nullable=True),
    )
    op.add_column(
        "tasks", sa.Column("last_execution_agent_sequence", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "last_execution_agent_sequence")
    op.drop_column("execution_runs", "execution_agent_sequence")
    # ### end Alembic commands ###
