"""Shared LLM output schemas for QA probing agents.

All schemas must be OpenAI strict-mode compatible:
- No dict[str, Any] fields
- No default values (stripped by schema_utils)
- All fields required or explicitly Optional (str | None)
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class QAFindingItem(BaseModel):
    """A single finding from a probing agent's LLM analysis."""

    finding_id: str
    severity: Literal["critical", "high", "medium", "low", "info"]
    category: Literal[
        "functional",
        "security",
        "performance",
        "usability",
        "accessibility",
        "compatibility",
        "reliability",
        "data_integrity",
        "boundary",
        "adversarial",
        "regression",
    ]
    title: str
    description: str
    reproduction_steps: list[str]
    affected_component: str | None
    auto_remediable: bool
    remediation_hint: str | None


class ProbeAnalysisOutput(BaseModel):
    """Full output from a probing agent's LLM call."""

    findings: list[QAFindingItem]
    probe_outcome: Literal["passed", "failed", "blocked", "skipped"]
    probe_summary: str


class RemediationItem(BaseModel):
    """A single remediation task proposed by the synthesis agent."""

    finding_id: str
    title: str
    description: str
    priority: Literal["critical", "high", "medium", "low"]
    estimated_effort: Literal["trivial", "small", "medium", "large"]


class SynthesisOutput(BaseModel):
    """Full output from the synthesis agent's LLM call."""

    verdict: Literal["passed", "failed", "blocked", "partial"]
    verdict_rationale: str
    remediation_tasks: list[RemediationItem]


# ── Phase 7 schemas ───────────────────────────────────────────────────────────


class TestScenario(BaseModel):
    """A single test scenario generated by functional_qa_agent (Pass 1)."""

    scenario_id: str
    test_type: Literal["happy_path", "edge_case", "error_case"]
    description: str
    test_inputs: str
    expected_behavior: str


class ScenarioList(BaseModel):
    """Output of functional_qa_agent Pass 1 — scenario generation."""

    scenarios: list[TestScenario]
    coverage_rationale: str


# ── Phase 8 schemas ───────────────────────────────────────────────────────────


class OWASPCheckItem(BaseModel):
    """Result for one OWASP Top 10 checklist item (security_qa_agent)."""

    check_id: str
    check_name: str
    passed: bool
    evidence: str


class OWASPAnalysisOutput(BaseModel):
    """Full output from security_qa_agent's OWASP checklist analysis."""

    check_results: list[OWASPCheckItem]
    findings: list[QAFindingItem]
    probe_outcome: Literal["passed", "failed", "blocked", "skipped"]
    probe_summary: str


# ── Phase 9 schemas ───────────────────────────────────────────────────────────


class RegressionAnalysisOutput(BaseModel):
    """Output of regression_qa_agent comparison between current and previous session."""

    new_findings: list[QAFindingItem]  # findings new in current run (regressions)
    resolved_count: int  # previous findings no longer present in current run
    probe_outcome: Literal["passed", "failed", "blocked", "skipped"]
    probe_summary: str
